### ISSUE TITLE
貌似没有效果

### ISSUE THREAD

**Issue by xingag** [cnzx219/android-uninstall-feedback#1]
在5.0和4.4.2上，分别卸载应用，没有任何的跳转

**Comment by CyberTianzun** [comment]
5.0和5.0以上的版本确实不行，android代码改了一些东西，孤儿进程不再能存活了。不过4.4.2是可以正常运行的，除了一些厂商深度定制的ROM可能会有一些问题，比如粗粮手机。
不过很感谢你能反馈这个问题，能留下你测试的4.4.2的机器的机型吗？

**Comment by xingag** [comment]
华为p6

**Comment by xingag** [comment]
不过，华为的手机也是经过定制的

**Comment by CyberTianzun** [comment]
我还是借一台这个机器验证一下结论。
之前有反编译华为的ROM发现会有的版本会强制删除360的App的.so文件。

**Comment by CyberTianzun** [comment]
已经适配
